# Generated by Django 4.0 on 2022-11-04 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.OneToOneField(db_column='genre', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='catalog.genre', to_field='genre'),
        ),
    ]
