# Generated by Django 4.0 on 2022-11-04 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_book_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='genre_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre_name',
            field=models.OneToOneField(db_column='genre', default='', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='catalog.genre', to_field='genre_name'),
            preserve_default=False,
        ),
    ]
