# Generated by Django 4.0 on 2022-11-04 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_genre_genre_genre_name_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre_name',
            field=models.ForeignKey(db_column='genre', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='catalog.genre', to_field='genre_name'),
        ),
    ]
