# Generated by Django 4.0 on 2022-11-05 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_book_genre_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, related_name='reviews', to='catalog.Book'),
        ),
        migrations.AddField(
            model_name='review',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
