# Generated by Django 4.0 on 2022-11-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_book_reviews_remove_user_reviews_review_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book_id',
            field=models.IntegerField(default=0, verbose_name='book id'),
        ),
    ]
