# Generated by Django 4.0 on 2022-11-05 01:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_review_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fav_books',
        ),
        migrations.AddField(
            model_name='book',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
    ]
